### ISSUE TITLE
Pedestrian behavior annotations do not match in xmls

### ISSUE THREAD

**Issue by v1t0** [ykotseruba/JAAD_dataset#9]
Hi,

I'm facing some errors while trying to generate the trajectory sequences using the pedestrian behaviour annotations (branch JAAD_2.0, commit be57a06480).
The error can be reproduced with the following commands:

```python
from jaad_data import JAAD
jaad_path = '/home/vito/workspace/JAAD/'
imdb = JAAD(data_path=jaad_path)
seq = imdb.generate_data_trajectory_sequence(image_set='train', seq_type='trajectory', sample_type='beh')
```
and here is the output:
```
---------------------------------------------------------                 
Generating action sequence data   
data_split_type: default          
height_rng: [0, inf]                                                      
squarify_ratio: 0                                                
kfold_params: {'num_folds': 5, 'fold': 1}                                 
subset: default                   
seq_type: trajectory                 
random_params: {'regen_data': False, 'val_data': True, 'ratios': None}    
fstride: 1                                                                
sample_type: beh                                                          
min_track_size: 15                                                        
---------------------------------------------------------
Generating database for jaad      
Getting annotations for video_0001                                        
Getting annotations for video_0002                                        
Getting annotations for video_0003                               
...
Getting annotations for video_0346
The database is written to /home/vito/workspace/JAAD/data_cache/jaad_database.pkl
---------------------------------------------------------        
Generating trajectory data
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/vito/workspace/JAAD/jaad_data.py", line 1031, in generate_data_trajectory_sequence
    sequence = self._get_trajectories(image_set, annot_database, **params)
  File "/home/vito/workspace/JAAD/jaad_data.py", line 1097, in _get_trajectories
    if annotations[vid]['ped_annotations'][pid]['attributes']['crossing'] == -1:
KeyError: 'crossing'
>>>
>>> import pdb
>>> pdb.pm()
> /home/vito/workspace/JAAD/jaad_data.py(1097)_get_trajectories()
-> if annotations[vid]['ped_annotations'][pid]['attributes']['crossing'] == -1:
(Pdb) list
1092                    ped_ids = [[pid]] * len(boxes)
1093
1094                    if params['sample_type'] == 'all':
1095                        intent = [[0]] * len(boxes)
1096                    else:
1097 ->                     if annotations[vid]['ped_annotations'][pid]['attributes']['crossing'] == -1:
1098                            intent = [[0]] * len(boxes)
1099                        else:
1100                            intent = [[1]] * len(boxes)
1101                    center = [self._get_center(b) for b in boxes]
1102
(Pdb) vid
'video_0001'
(Pdb) pid
'0_1_1b'
(Pdb)
```

It looks like `annotations/` and `annotations_attributes/` do not match.
For example, `annotations_attributes/video_0001_attributes.xml` lists two pedestrians: "0_1_2b" (old_id="pedestrian2") and "0_1_3b" (old_id="pedestrian1"). However `annotations/video_0001.xml` includes only two pedestrians with behavior: "0_1_1b" (old_id="pedestrian1") and "0_1_3b" (old_id="pedestrian2").

I'm afraid video_0001 is not the only mismatch... from the repo hisory I guess something must have happened with commit 3f1931510. If I checkout the previous commit (0e819c68ce) the above python commands complete succesfully.

Could you please check if everything is ok with the annotations or tell me if I am using the interface in the wrong way?

Thanks!
Vito

**Comment by aras62** [comment]
Hi Vito,

Thank you for bringing that into our attention. The problem was with the id mismatch between annotations and annotations_attributes. I fixed the ids in the annotations. Please pull the latest commit and that should resolve the issue

**Comment by v1t0** [comment]
Hi Amir,

Thanks for the prompt reply, it works now.
I'm closing this issue.

Best regards,
Vito
